CREATE TABLE IF NOT EXISTS public.core_tts_pronunciation (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_text character varying(120) NOT NULL,
    spoken_text character varying(240) NOT NULL,
    npc_names character varying(512) NOT NULL DEFAULT '',
    races character varying(512) NOT NULL DEFAULT '',
    oghma_tags character varying(512) NOT NULL DEFAULT '',
    is_builtin boolean NOT NULL DEFAULT FALSE,
    enabled boolean NOT NULL DEFAULT TRUE,
    deleted boolean NOT NULL DEFAULT FALSE,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT core_tts_pronunciation_source_not_blank CHECK (BTRIM(source_text) <> ''),
    CONSTRAINT core_tts_pronunciation_spoken_not_blank CHECK (BTRIM(spoken_text) <> '')
);

ALTER TABLE public.core_tts_pronunciation
    ADD COLUMN IF NOT EXISTS npc_names character varying(512) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS races character varying(512) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS deleted boolean NOT NULL DEFAULT FALSE;

DROP INDEX IF EXISTS public.core_tts_pronunciation_unique_entry;
CREATE UNIQUE INDEX IF NOT EXISTS core_tts_pronunciation_unique_entry
    ON public.core_tts_pronunciation (
        LOWER(source_text),
        MD5(LOWER(npc_names) || E'\x1f' || LOWER(races) || E'\x1f' || LOWER(oghma_tags)),
        is_builtin
    );
